(defpackage #:shopping-lisp.constants
  (:use #:cl))

(in-package #:shopping-lisp.constants)

(defconstant +BACKEND-VERSION+ 1.0)
(defconstant +API-SUCCESS-LIST+ 1000)
(defconstant +API-SUCCESS-LIST-EMPTY+ 1001)
(defconstant +API-SUCCESS-UPDATE+ 1002)
(defconstant +API-SUCCESS-FAVORITE+ 1003)
(defconstant +API-SUCCESS-DELETE+ 1004)
(defconstant +API-SUCCESS-SAVE+ 1005)
(defconstant +API-SUCCESS-CLEAR+ 1006)
(defconstant +API-ERROR-SERVER+ 5000)
(defconstant +API-ERROR-404+ 5001)
(defconstant +API-ERROR-403+ 5002)
(defconstant +API-ERROR-MISSING-FUNCTION+ 5003)
(defconstant +API-ERROR-NO-DATABASE+ 5004)
(defconstant +API-ERROR-CONFIG+ 5005)
(defconstant +API-ERROR-UNKNOWN+ 5006)
(defconstant +API-ERROR-DATABASE-CONNECT+ 5012)
(defconstant +API-ERROR-MISSING-PARAMETER+ 5013)
(defconstant +API-ERROR-FUNCTION-NOT-SPECIFIED+ 5014)
(defconstant +API-ERROR-NOT-CONFIGURED+ 5015)

(defconstant +API-ERROR-UPDATE+ 6001)
(defconstant +API-ERROR-FAVORITE+ 6002)
(defconstant +API-ERROR-DELETE+ 6003)
(defconstant +API-ERROR-SAVE+ 6004)
(defconstant +API-ERROR-CLEAR+ 6005)
